/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package radingame;
import java.lang.Object;
import java.util.*;
import javax.swing.*;
import javax.swing.Timer;
import java.awt.event.*;

/**
 *
 * @author Zulox
 */
public class Game extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Game
     */
    
    private int[]cardValue;
    private int maxPair = 4;
    private int maxCard = maxPair * 2;
    private JButton[] btn = new JButton[maxCard];
    
    private int temp1 = -1;
    private int temp2 = -2;
    private int cardStatus = -1;
    private int tempCardChoosen1;
    private int tempCardChoosen2;
    
    private int [] score = new int[3];
    private int PlayerTurn = 2;
    
    private int RemainingPair = 4;
    
    
    public Game() {
        initComponents();
        addbutton();
        assignValue();
    
        
    }
    
    private void addbutton(){
    
        for(int j = 0; j < maxCard ; j++){
                btn[j] = new JButton();
                pnl_Button.add(btn[j]);
		btn[j].addActionListener((ActionListener) this);    	
	}
    }
    
    public void actionPerformed(ActionEvent evt){
     for(int j = 0; j <  maxCard; j++){
        if(evt.getSource() == btn[j]){
                bararaize(j);
        }
    } 
    }
    
    
    private void bararaize(int identifier){
        System.out.println( ""  );
        if( cardStatus == -1 )
        {
            temp1 = cardValue[identifier];
            btn[identifier].setText("" +temp1);
            tempCardChoosen1 = identifier;
            System.out.println( temp1 + "  ,  " + temp2  + "   "  +cardStatus);
            btn[tempCardChoosen1].setEnabled(false);
            cardStatus = -2;
        }
        else if(  cardStatus == -2 )
        {
            temp2 = cardValue[identifier];
            btn[identifier].setText("" +temp2);
            tempCardChoosen2 = identifier;
            btn[tempCardChoosen2].setEnabled(false);
            System.out.println( temp1 + "  ,  " + temp2  + "   "  +cardStatus);
            cardStatus = -3;
        }
        
        
        if( cardStatus == -3){
            
           if(temp1 != temp2){ 
             Timer timer = new Timer(0, (ActionEvent evt) -> {
             btn[tempCardChoosen1].setText("");
             btn[tempCardChoosen1].setEnabled(true);
             
             btn[tempCardChoosen2].setText("");
             btn[tempCardChoosen2].setEnabled(true);
             System.out.println( temp1 + "  ,  " + temp2  + "   "  +cardStatus);
             
             temp1 = -1;
             temp2 = -2;
             cardStatus = -1; 
                 
             });
                  timer.setInitialDelay(1200); //wait one second
                  timer.setRepeats(false); //only once
                  timer.start();

     
           }
           
           if(temp1 == temp2){
                temp1 = -1;
                temp2 = -2;
                cardStatus = -1; 
                
                RemainingPair--;
                
                if(RemainingPair == 0){
                 JOptionPane.showMessageDialog(null, "Game Over" );
                }
           }
        }
        
       
    }
    
    private void assignValue(){
        Random rand = new Random();
        

        int min = 1;
       
        
        int[] limitNum = new int[maxPair];      
        Arrays.fill(limitNum, 2);
        
        
        
        cardValue = new int[maxCard];
         
        boolean proceed = false;
         
        int tempnum;
        int z = 0;
        int remainingCard = maxCard;
         do{
             tempnum = rand.nextInt((maxPair - min) + 1) + min;
             
             if(limitNum[tempnum-1] != 0){
                 
                 cardValue[z] = tempnum;
                 limitNum[tempnum-1] -= 1;
                 z++;
                 remainingCard--;
             }
             if(remainingCard == 0){
                 proceed = true;
             }
     
                 
         
         }while(proceed == false);
         
        for(int i = 0 ; i < maxCard ; i++){
          System.out.print("    " + cardValue[i]);
        }
      
    }

    /**
     * !!!!!!!!!!!DONT GO HERE, This is auto generated, it doesnt concern you, especially you radin because you stupid crazy people!!!!!!!
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnl_Button = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Turn : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Player 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Player 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("Player 2");

        jButton1.setText("Restart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_InfoLayout = new javax.swing.GroupLayout(pnl_Info);
        pnl_Info.setLayout(pnl_InfoLayout);
        pnl_InfoLayout.setHorizontalGroup(
            pnl_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(pnl_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_InfoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_InfoLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        pnl_InfoLayout.setVerticalGroup(
            pnl_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_InfoLayout.createSequentialGroup()
                .addGroup(pnl_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_InfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(pnl_InfoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnl_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnl_Button.setLayout(new java.awt.GridLayout(4, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
      
        new Game().setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnl_Button;
    private javax.swing.JPanel pnl_Info;
    // End of variables declaration//GEN-END:variables
}
